### ISSUE TITLE
Incorrect spacing on ɯ in Libertine Sans

### ISSUE THREAD

**Issue by Ketsuban** [khaledhosny/libertine#1]
(This is actually a bug in Linux Biolinum which Libertine has inherited - I don't want to go to the trouble of registering on Sourceforge to report something this trivial, but the email address they provide bounced when I tried to report it like that. If you could push it upstream for me I'd be grateful.)

In Libertine Sans Regular and Libertine Sans Italic (and the corresponding Linux Biolinum faces) LATIN SMALL LETTER TURNED M (U+026F) has the wrong width, causing the glyph to overlap with its neighbour.

**Comment by khaledhosny** [comment]
I fixed it, but I can not guarantee that it will be merged with upstream (or any else from what I’m doing, for that matter).

**Comment by Ketsuban** [comment]
I understand. :) Thanks for attending to this so promptly.
