### ISSUE TITLE
Kerning between small caps P and A

### ISSUE THREAD

**Issue by SverreStausland** [khaledhosny/libertine#3]
The space between small caps P and A is too large. The space is slightly narrower with the libertine package.

\documentclass{article}
%% With lualatex
\usepackage{fontspec}
\setmainfont{Libertine Serif}[SmallCapsFeatures = {Renderer = Basic, Letters = SmallCaps}]
%%

%% With latex
%\usepackage{libertine}
%%

\begin{document}
\textsc{ipa}
\end{document}

![ipa](https://cloud.githubusercontent.com/assets/4471032/9428225/00b3cd08-49a5-11e5-834c-2b480008cabd.png)
![ipa2](https://cloud.githubusercontent.com/assets/4471032/9428228/3021f6c8-49a5-11e5-95b7-f88e12724cc2.png)

**Comment by khaledhosny** [comment]
Libertine uses class based kerning, which does not seem to be supported by the base mode of luaotfload. If you drop `Renderer = Basic` you will get the kerning.

**Comment by SverreStausland** [comment]
I see. Unfortunately 'Renderer = Basic' is needed in lualatex when
compiling with 'microptype':
http://tex.stackexchange.com/questions/132873/microtype-tracking-disables-small-caps-in-lualatex

I'll switch to xelatex, then.
