### ISSUE TITLE
Access f with short arm

### ISSUE THREAD

**Issue by SverreStausland** [khaledhosny/libertine#4]
In German typography, ligatures are suppressed across morpheme boundaries. In a word like "Auflage", 'edition', there should be no fl-ligature, as this word is composed from the prefix 'auf-' and the noun 'Lage'. This is the reason for the creation of the selnolig package (https://www.ctan.org/pkg/selnolig).

Suppressing a ligature is often not enough, though, since this will often just cause the regular characters to collide. When suppressing a ligature, it is often necessary to access alternative glyphs. In Linux Libertine, there is an alternative glyph of 'f' that has a shorter arm so that it doesn't collide with a following character. I've found documentation that indicates that this was once accessed through an OpenType feature, but it was later removed, yet the glyph stayed in the font, now accessible in the PUA.

I can therefore use the short armed 'f' by accessing it directly. Example:
````tex
\documentclass{article}
\usepackage{fontspec}
\setmainfont{LinLibertine_Rah}[Path=L:/fonts/LinLibertine5.3.0/]
\begin{document}
Auflage -- Au\char"E0E0lage
\end{document}
````
It's dirty, because this probably breaks hyphenation, and the output 'f' will probably not map to the regular 'f' when copying and searching in the pdf.

But in Libertine Serif, the glyph has been moved into the unencoded area, and now it's not accessible in any way -- not via an OpenType feature, and not by typing it directly.
````tex
\documentclass{article}
\usepackage{fontspec}
\setmainfont{LinLibertine_Rah}[Path=L:/fonts/LinLibertine5.3.0/]
\newfontfamily{\libertine}{libertineserif-regular}[Path=L:/fonts/libertine-master02/, Ligatures = TeX]
\begin{document}
Linux Libertine:

Auflage -- Au\char"E0E0lage\\

Libertine Serif:

{\libertine{Auflage} -- ?}
\end{document}
````
Ideally there should be an OpenType feature that would allow the short armed 'f' to be accessed, one that would correctly map to Unicode 'f' when copying and searching in the pdf.

<img width="175" alt="libertine" src="https://cloud.githubusercontent.com/assets/4471032/9963937/f2312eae-5e2d-11e5-9981-259d2b1cfa13.png">

EDIT: The glyph is named "f.short" in both fonts. It's probably possible with LuaTeX to write some fancy code that will replace "f" with "f.short", but I think an OpenType feature would be a better way to do it.

**Comment by khaledhosny** [comment]
The `f.short` glyph is used in contextual substitutions like in `fT`, so it is accessible when the right context is used. I have made all alternate glyphs accessible via the `aalt` feature as well, so you can now do something like:
````
hb-view libertineserif-regular.otf Auflage --features="-liga[2:4],+aalt[2]=3"
````
and get
![fshort](https://cloud.githubusercontent.com/assets/93914/9967956/fea7cdba-5e45-11e5-97c9-c27d01301a02.png)
but I don’t think you can control features on just parts of the text (in a way like this) in any of the existing TeX engines. However, what you propably need is that when `fi` or `fl` are not ligated is that the short alternate is automatically used, so I’ll try to do this.

**Comment by georgd** [comment]
In EB Garamond I addressed this issue by providing a calt feature that contains contextual replacement for \f before glyphs it could coliide with with \f.short and also for \f before ZWNJ before glyphs it could collide with. While using ZWNJ to suppress ligatures isn’t wide spread in latin script, it might gain importance with wider distribution of the new german standard keyboard which provides an easy key stroke for it. Also, selnolig uses ZWNJ for this purpose so it seems very useful to me.

**Comment by khaledhosny** [comment]
With this commit, suppressing the `liga` feature or using ZWNJ gives short f.

````
hb-view libertineserif-regular.otf Auflage --features="-liga[2:4]
````

````
hb-view libertineserif-regular.otf Auf‌lage
````

@georgd I didn’t match ZWNJ in my lookups because HarfBuzz is smart enough to handle it properly and I think engines that don’t do so are not Unicode complaint (furthermore most engine will replace ZWNJ and other control characters by the space glyph index).

**Comment by khaledhosny** [comment]
Your LaTeX example can now be, compare the two lines (the use of \kern in the second line will suppress the ligature but will break the word as well so that OpenType layout will not apply):
````tex
\documentclass{article}
\usepackage{fontspec}
\setmainfont{libertineserif-regular.otf}
\begin{document}
Auflage – Auf\char"200C lage

Auflage – Auf\kern0pt lage
\end{document}
````

**Comment by SverreStausland** [comment]
I believe the substitution of the long armed 'f' with the short arm 'f' is unnecessary when the following character is 'f' and 't'. The 'ft'-ligature is created by joining their cross strokes, so it doesn't really make sense to shorten the arm of the 'f' anyway. A non-ligated 'ff' doesn't have colliding glyphs, and it looks in fact much more appropriate than a sequence 'ff' in which the first 'f' has a short arm.

Removing the short armed 'f' in non-ligated 'ff'-sequences would also fix the issue of what to do in words like 'auffliegen' (= auf + fliegen), in which there shouldn't be a 'ff' ligature, but there should be a 'fl' ligature. I wouldn't even know how to get a short armed 'f' plus a 'fl' ligature here anyway.

Of course, we still don't have a solution for compound words like 'Schiffjäger' (Schiff + jäger), but that's because the font doesn't provide a 'ff' ligature with a final short-armed 'f' to begin with.

	\documentclass{article}
	\usepackage{fontspec}
	\usepackage[ngerman]{babel}
		\babelhyphenation[ngerman]{auf-fallen}
	\setmainfont{libertineserif-regular}[Path=L:/fonts/libertine-master03/, Ligatures = {TeX, Common}]
	\newfontfamily{\libertinetwo}{libertineserif-regular}[Path=L:/fonts/libertine-master03/, Ligatures = {TeX, NoCommon}]
	\newfontfamily{\libertinethree}{libertineserif-regular}[Path=L:/fonts/libertine-master03/, Ligatures = {TeX, NoCommon}, Contextuals = Alternate]
	\newcommand{\yes}{\char"2714}
	\newcommand{\no}{\char"2718}
	\begin{document}
	Aufbau \no

	{\libertinetwo Aufbau} \no

	{\libertinethree Aufbau} \yes\\

	auffallen \no

	{\libertinetwo auffallen} \yes

	{\libertinethree auffallen} \no\\

	aufhören \no

	{\libertinetwo aufhören} \no

	{\libertinethree aufhören} \yes\\

	aufintegrieren \no

	{\libertinetwo aufintegrieren} \no

	{\libertinethree aufintegrieren} \yes\\

	aufjagen \no

	{\libertinetwo aufjagen} \no

	{\libertinethree aufjagen} \yes\\

	Aufklärung \no

	{\libertinetwo Aufklärung} \no

	{\libertinethree Aufklärung} \yes\\

	Auflage \no

	{\libertinetwo Auflage} \no

	{\libertinethree Auflage} \yes\\

	Auftrag \no

	{\libertinetwo Auftrag} \yes

	{\libertinethree Auftrag} \no\\

	auffliegen \no

	au{\libertinetwo f}fliegen \yes

	au{\libertinethree f}fliegen ??\\

	Schiffjäger \no

	Schiff{\libertinetwo j}äger \no

	Schiff{\libertinethree j}äger \no

	\end{document}

<img width="82" alt="libertine" src="https://cloud.githubusercontent.com/assets/4471032/10020838/49584432-6145-11e5-9535-9565e65d1af9.png">

**Comment by khaledhosny** [comment]
We do in fact have a short ff ligature, also switching the font in the middle of the word (like in `au{\libertinetwo f}fliegen` will break any OpenType interaction between the parts as it does not happen across font boundaries). Also I don’t understand all your yes's no's, and your `\libertinetwo` and `\libertinethree` fonts should behave the same as contextual alternates are on by default (please test with XeTeX, luaotfload is unreliable and you can’t tell if what you are seeing is a bug in it or in the font).

**Comment by SverreStausland** [comment]
Sorry for the late reply.

1. My yes/no macros (without check mark and cross outputs) are only meant to illustrate which glyph combinations I think look acceptable or not. In short, when ligatures are turned off, then the short f should appear before <b h i j k l>, but not before <f t>. I hope you agree?

2. I didn't know that luaotfload was unreliable here. Adding `RawFeature = -calt` to `\libertinetwo` will make xelatex produce the same output as lualatex did in my previous example.

3. You're absolutely right - there is an 'ff' ligature with a final short f in the font. So this is the one that should be chosen for the combinations of ff + <b h i j k l> across morpheme boundaries. How should this be implemented?

**Comment by khaledhosny** [comment]
On Mon, Sep 28, 2015 at 07:38:45AM -0700, SverreStausland wrote:
> Sorry for the late reply.
> 
> 1. My yes/no macros (without check mark and cross outputs) are only meant to illustrate which glyph combinations I think look acceptable or not. In short, when ligatures are turned off, then the short f should appear before <b h i j k l>, but not before <f t>. I hope you agree?

Sure, I was confused because I was looking at the XeTeX output where it showed no difference. 

> 3. You're absolutely right - there is an 'ff' ligature with a final short f in the font. So this is the one that should be chosen for the combinations of ff + <b h i j k l> across morpheme boundaries. How should this be implemented?

It should just work. To disable the ligatures anywhere just insert the ZWNJ character, that is the recommended Unicode way, and the font should give you the alternate glyphs (in XeTeX and other Unicode-compliant layout engins at least, luaotfload is a different story and I don’t know what works their). Switching fonts to disable the ligatures (or using `\addfontfeatures` which works be temporarily creating new fonts) will not allow the contextual substitution to take place as the layout engines will not see the whole word but fragments of it at a time.

**Comment by SverreStausland** [comment]
On Mon, Sep 28, 2015 at 9:00 PM, Khaled Hosny <notifications@github.com>
wrote:

> On Mon, Sep 28, 2015 at 07:38:45AM -0700, SverreStausland wrote:
>


> > 3. You're absolutely right - there is an 'ff' ligature with a final
> short f in the font. So this is the one that should be chosen for the
> combinations of ff + <b h i j k l> across morpheme boundaries. How should
> this be implemented?
>
> It should just work. To disable the ligatures anywhere just insert the
> ZWNJ character, that is the recommended Unicode way, and the font should
> give you the alternate glyphs


Why does this work with the libertine font when it doesn't have the ZWNJ
character (U+200C)? It has U+200A and U+200B, but not U+200C.

**Comment by SverreStausland** [comment]
Also, I see that you removed the short f glyph before <t>, but not
before <f>. I think it should be removed before <f> (plus its
variations and long s) as well.

**Comment by khaledhosny** [comment]
> > It should just work. To disable the ligatures anywhere just insert the
> > ZWNJ character, that is the recommended Unicode way, and the font should
> > give you the alternate glyphs
> 
> Why does this work with the libertine font when it doesn't have the ZWNJ
> character (U+200C)? It has U+200A and U+200B, but not U+200C.

ZWNJ is a control character and Unicode-compliant layout engines do not
need the font to have a glyph for it to handle it correctly (the glyph
is almost always ignored anyway and a zero width space is inserted in
its place).

**Comment by khaledhosny** [comment]
> Also, I see that you removed the short f glyph before <t>, but not
> before <f>. I think it should be removed before <f> (plus its
> variations and long s) as well.

You are right, it looks fine without the short f here, fixed.
