### ISSUE TITLE
Wrong kerning for 'fj' in sans italic

### ISSUE THREAD

**Issue by SverreStausland** [khaledhosny/libertine#5]
The kerning between the characters 'f' and 'j' looks correct in sans regular, in that the kerning appears to be the same as for 'fi'. But the kerning is wrong for sans italic:

	\documentclass{article}
	\usepackage{fontspec}
	\setmainfont{libertinesans-}[
		UprightFont = *regular,
		ItalicFont = *italic]
	\begin{document}
	fi \textit{fi}

	fj \textit{fj}
	\end{document}
<img width="106" alt="fj" src="https://cloud.githubusercontent.com/assets/4471032/10165124/c1ca6274-66bd-11e5-9ccf-f98145760648.png">

**Comment by khaledhosny** [comment]
That is because the italic font is missing the short f, one of the many Linux Libertine inconsistencies, otherwise both fonts have the same bogus fj kerning.
